# add your settings here (overriding the defaults)

biocypher:
  offline: true
  schema_config_path: "config/schema_config.yaml"
  debug: false

neo4j:
  delimiter: "\t"
  array_delimiter: "|"
  skip_duplicate_nodes: true
  skip_bad_relationships: true
