# add your desired knowledge graph components here

protein:
    represented_as: node
    preferred_id: uniprot
    label_in_input: protein

receptor protein:
    is_a: protein
    represented_as: node
    preferred_id: uniprot
    label_in_input: receptor

ligand protein:
    is_a: protein
    represented_as: node
    preferred_id: uniprot
    label_in_input: ligand

disease:
    represented_as: node
    preferred_id: doid
    label_in_input: do_disease
    
protein interaction:
    is_a: pairwise molecular interaction
    represented_as: edge
    label_in_input: protein_protein_interaction

protein to disease association:
    is_a: association
    represented_as: edge
    label_in_input: protein_disease_association
