gene:
  represented_as: node
  preferred_id: ensembl
  label_in_input: [gene, ensembl]
  properties:    
    gene_names: str[]
    xref_kegg: str[]
    xref_ensembl: str[]
    ensembl_gene_ids: str[]

disease:
  represented_as: node
  preferred_id: [mondo, efo, hp, orphanet, otar, oba, ncit, doid, obi, ogms]
  label_in_input: [mondo, efo, hp, orphanet, otar, oba, ncit, doid, obi, ogms]
  properties:
    code: str
    name: str
    description: str
    ontology: str

protein:
  represented_as: node
  preferred_id: uniprot
  label_in_input: protein
  properties:
    secondary_ids: str[]
    length: int
    mass: int
    protein_name: str[]
    xref_proteomes: str[]
    organism_id: int
    ec: str[]
    virus_hosts: int[]

ligand protein:
  represented_as: node
  is_a: protein
  label_in_input: ligand
  properties:
    secondary_ids: str[]
    length: int
    mass: int
    protein_names: str[]
    proteome: str[]
    organism_id: int
    ec: str[]
    virus_hosts: int[] 

receptor protein:
  represented_as: node
  is_a: protein
  label_in_input: receptor
  properties:
    secondary_ids: str[]
    length: int
    mass: int
    protein_names: str[]
    proteome: str[]
    organism_id: int
    ec: str[]
    virus_hosts: int[] 
  
organism taxon:
  represented_as: node
  preferred_id: ncbitaxon
  label_in_input: organism_name
  properties:
    organism: str

cellular component:
  represented_as: node
  label_in_input: location
  
gene to protein relationship:
  is_a: gene to gene product relationship
  represented_as: edge
  label_as_edge: Encodes
  preferred_id: id
  source: gene
  target: protein
  label_in_input: Encodes
  
protein to organism taxon association:
  is_a: association
  represented_as: edge
  label_as_edge: Belongs_To
  preferred_id: id
  source: protein
  target: organismTaxon
  label_in_input: Belongs_To  
  
post translational interaction:
  is_a: association
  represented_as: edge
  label_as_edge: Interacts_With
  preferred_id: id
  source: protein
  target: protein
  label_in_input: Interacts_With
  properties:    
    source: str[]
    pubmed_id: int[]
    method: str
    interaction_type: str
    intact_score: float
    string_combined_score: int
    string_physical_combined_score: int    
    
protein to cellular component association: 
  represented_as: edge
  is_a: association
  label_in_input: Found_in

gene to disease association:
  represented_as: edge
  preferred_id: [
    affected pathway, 
    somatic mutation, 
    genetic association, 
    literature,
    animal model,
    known drug,
    rna expression,
  ]
  label_in_input: [
    affected_pathway, 
    somatic_mutation, 
    genetic_association,
    literature,
    animal_model,
    known_drug,
    rna_expression,
  ]
  properties:
    literature: str[]
    score: double

gene to protein relationship:
  is_a: gene to gene product relationship
  represented_as: edge
  label_in_input: Encodes